### ISSUE TITLE
BUG: Settings: Edit in cluster item does not show IP-address

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#1]
When you have cluster items and try to edit one, it does not show IP-address (field is empty)

![image](https://cloud.githubusercontent.com/assets/17140545/13050088/cfe896b0-d3f9-11e5-82a9-550a4fca3673.png)

![image](https://cloud.githubusercontent.com/assets/17140545/13050104/e5196794-d3f9-11e5-834d-70b75661bcc1.png)

**Comment by viliman** [comment]
Technically this can be closed only when tested against official release and confirmed. But don't worry if we have problem with this the testing team will open new ticket :) Thanks for the fix anyway!
