### ISSUE TITLE
BUG: Edit saved playlist

### ISSUE THREAD

**Issue by TaruVare** [rameplayerorg/rameplayer-defects#10]
Test case: PL_IMPT_4
Browser: Chrome, version 49.0.2623.87 m,  Mozilla Firefox 35.0.1 and IE 11

There is no option/function to add new items to the saved playlist from work list.

[Save work list and My playlist fail 170316.txt](https://github.com/rameplayerorg/rameplayer-defects/files/177475/Save.work.list.and.My.playlist.fail.170316.txt)

**Comment by iqqmuT** [comment]
With referred commit user can now drag and drop items across playlists. Currently it works so that item will be appended as the last item in the destination playlist. Would require backend changes to support adding to a specific index in destination playlist.

**Comment by TaruVare** [comment]
I was not able to drag and drop items between playlists (with IE11 nor FF, with Chrome whole dragging still don't work). It looks like item can be dragged to another playlist, but it doesn't appear to the destination playlist. Tested with firmware 0.7.2.

**Comment by iqqmuT** [comment]
Git commit was not included in firmware 0.7.2 yet, so please wait for the next release. :)

**Comment by TaruVare** [comment]
Adding new item to a saved playlist has some issues:
1. With Chrome and IE browsers, after dragging new item to the saved playlist, the only item that can be rearranged after that is the new item.
2. With Firefox new item can be moved to the bottom of the list, but if I rearrange items in playlist after that or try to add another new item, then the already added item disappears from the saved playlist.
   Steps to reproduce:
3. Save a playlist.
4. Add new item to the work list.
5. Move new item to the saved playlist by dragging it with a mouse.
6. Rearrange any item in saved playlist or move another item from work list to the saved playlist.
   Result: all items added after saving playlist at the first time disappears from the saved playlist.

**Comment by HassuX** [comment]
Addition to this, it's not possible to 'move' playlist between USB-disk and RAME.

So if you first save playlist to RAME, then edit it to save it to USB-disk, it actually does nothing.

**Comment by TaruVare** [comment]
Currently added items appear as the last on the list, but those disappear when rebooting Rame

**Comment by viliman** [comment]
Need support from backend

**Comment by TaruVare** [comment]
Fixed in 0.91

**Comment by TaruVare** [comment]
Sorry, not fixed 0.91

**Comment by TaruVare** [comment]
IE and Firefox works now, but in Chrome there is a new issue:

Adding new item to the saved playlist, adds the same item to the list multiple times.

Steps to reproduce:
1. Add items to the work list
2. Create a saved play list
3. Add one new item to the work list
4. Drag and drop new item from the work list to the saved playlist
5. Added item appears multiple times to the saved play list. See screenshot below

![add new item to saved playlist_fail_0506](https://cloud.githubusercontent.com/assets/17190958/15804914/3e4043ea-2b22-11e6-9dc1-24b03452b9ed.PNG)

**Comment by iqqmuT** [comment]
Backend is not sending any HTTP status code when item is dropped to a new playlist:
`POST http://backend/lists/playlistid/items`

Not sure if that's the root cause of this bug but at least it needs to be fixed.

**Comment by iqqmuT** [comment]
Commit above seems to fix the bug appeared on Chrome

**Comment by TaruVare** [comment]
Fixed in 1.0.3
