### ISSUE TITLE
BUG: Remove saved playlist

### ISSUE THREAD

**Issue by TaruVare** [rameplayerorg/rameplayer-defects#12]
Test case: PL_IMPT_8
Browser: Chrome, Mozilla Firefox 35.0.1 and IE 11

When selecting Remove from saved playlist, the playlist is emptied but it doesn't disappear fully. 

![remove saved playlist fail 170316](https://cloud.githubusercontent.com/assets/17190958/13840749/1ffd6dc4-ec2d-11e5-9ecc-ae611b2bbb99.PNG)

**Comment by iqqmuT** [comment]
I could not reproduce this bug with 0.7.2 and FF 45 and Chrome 49. Playlist was removed ok.

**Comment by TaruVare** [comment]
The bug appears to be related to removal of saved playlist when there are more than one saved playlists. After the reboot (when playlists are initally empty) removing last saved list removes all saved lists and leaves this empty line. After that removing works ok. I tested with Chrome, FF and IE11.

Steps to reproduce:
Reboot RamePlayer (so that playlist is empty and no saved playlists appear)
Add multiple items (e.g. English) to the Work list and Save list with name 1
Clear work list
Add multiple other items (e.g. Finnish) to the Work list and Save list with name 2
Select saved list which appears as last, click Remove
Both saved playlists are removed and line "Playlist is empty" is visible

**Comment by TaruVare** [comment]
Firefox browser don't reproduce this issue any more. IE 11 and Chrome still do.

**Comment by TaruVare** [comment]
Issue exists now again in all browsers. But when RaMe player is rebooted, then not removed playlist appears back. Steps to reproduce as earlier, but add reboot as a final step. See attached pictures to see situation after removing second saved playlist and after reboot.

![remove saved list_results_080516](https://cloud.githubusercontent.com/assets/17190958/15098802/4cecbc3c-154e-11e6-833d-0bda94fe3a52.PNG)

![remove saved list_after reboot_080516](https://cloud.githubusercontent.com/assets/17190958/15098803/520b6740-154e-11e6-8e0c-e35f6b4b5028.PNG)

**Comment by fabled** [comment]
relevant fix in 0.8.2, please verify

**Comment by TaruVare** [comment]
Version 0.8.2 don't have USB visible at all. I cannot proceed with testing, when all my test items were on USB.

**Comment by McLad76** [comment]
Works in 0.8.3

**Comment by TaruVare** [comment]
Agree, verified in IE 11, Firefox and Chrome
