### ISSUE TITLE
BUG: first item played in directory generates an I2S SYNC error to the log

### ISSUE THREAD

**Issue by HablasNapa** [rameplayerorg/rameplayer-defects#16]
Mar 19 10:25:52 rame kern.info kernel: [ 4743.821823] usb 1-1.5: new high-speed USB device number 8 using dwc_otg
Mar 19 10:25:52 rame kern.info kernel: [ 4743.924356] usb 1-1.5: New USB device found, idVendor=090c, idProduct=1000
Mar 19 10:25:52 rame kern.info kernel: [ 4743.924373] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Mar 19 10:25:52 rame kern.info kernel: [ 4743.924383] usb 1-1.5: Product: Flash Disk
Mar 19 10:25:52 rame kern.info kernel: [ 4743.924393] usb 1-1.5: Manufacturer: USB
Mar 19 10:25:52 rame kern.info kernel: [ 4743.924403] usb 1-1.5: SerialNumber: FBG1108230232244
Mar 19 10:25:52 rame kern.info kernel: [ 4743.925214] usb-storage 1-1.5:1.0: USB Mass Storage device detected
Mar 19 10:25:52 rame kern.info kernel: [ 4743.926891] scsi host4: usb-storage 1-1.5:1.0
Mar 19 10:25:53 rame kern.notice kernel: [ 4745.164929] scsi 4:0:0:0: Direct-Access     USB      Flash Disk       1100 PQ: 0 ANSI: 4
Mar 19 10:25:53 rame kern.notice kernel: [ 4745.166701] sd 4:0:0:0: [sdb] 3915776 512-byte logical blocks: (2.00 GB/1.87 GiB)
Mar 19 10:25:53 rame kern.notice kernel: [ 4745.167473] sd 4:0:0:0: [sdb] Write Protect is off
Mar 19 10:25:53 rame kern.debug kernel: [ 4745.167492] sd 4:0:0:0: [sdb] Mode Sense: 43 00 00 00
Mar 19 10:25:53 rame kern.err kernel: [ 4745.169727] sd 4:0:0:0: [sdb] No Caching mode page found
Mar 19 10:25:53 rame kern.err kernel: [ 4745.169752] sd 4:0:0:0: [sdb] Assuming drive cache: write through
Mar 19 10:25:53 rame kern.info kernel: [ 4745.174361]  sdb: sdb1
Mar 19 10:25:53 rame kern.notice kernel: [ 4745.177708] sd 4:0:0:0: [sdb] Attached SCSI removable disk
Mar 19 10:26:00 rame user.info RAME: Player: sending play command, cursor 1458378423001122
Mar 19 10:26:00 rame user.info RAME: Stopped
Mar 19 10:26:00 rame user.info RAME: Playing file:////media/sdb1/musiikit/iasn_FI_016.mp3
Mar 19 10:26:01 rame kern.err kernel: [ 4752.943999] bcm2708-i2s 3f203000.i2s: I2S SYNC error!
Mar 19 10:26:04 rame user.info RAME: Stopped file:////media/sdb1/musiikit/iasn_FI_016.mp3
Mar 19 10:26:04 rame user.info RAME: Playing
Mar 19 10:26:09 rame user.info RAME: Player: sending play command, cursor 1458378423001136
Mar 19 10:26:09 rame user.info RAME: Stopped
Mar 19 10:26:09 rame user.info RAME: Playing file:////media/sdb1/musiikit/iasn_FI_038.mp3
Mar 19 10:26:10 rame kern.err kernel: [ 4761.684356] bcm2708-i2s 3f203000.i2s: I2S SYNC error!
Mar 19 10:26:12 rame user.info RAME: Stopped file:////media/sdb1/musiikit/iasn_FI_038.mp3
Mar 19 10:26:12 rame user.info RAME: Playing
Mar 19 10:26:15 rame user.info RAME: Player: sending play command, cursor 1458378423001138
Mar 19 10:26:15 rame user.info RAME: Stopped
Mar 19 10:26:15 rame user.info RAME: Playing file:////media/sdb1/musiikit/iasn_FI_042.mp3
Mar 19 10:26:22 rame user.info RAME: Stopped file:////media/sdb1/musiikit/iasn_FI_042.mp3
Mar 19 10:26:22 rame user.info RAME: Playing
Mar 19 10:28:00 rame user.info RAME: Player: sending play command, cursor 1458378423001112
Mar 19 10:28:00 rame user.info RAME: Stopped
Mar 19 10:28:00 rame user.info RAME: Playing file:////media/sdb1/musiikit/iasn_FI_008.mp3
Mar 19 10:28:01 rame kern.err kernel: [ 4872.774157] bcm2708-i2s 3f203000.i2s: I2S SYNC error!
Mar 19 10:28:03 rame user.info RAME: Stopped file:////media/sdb1/musiikit/iasn_FI_008.mp3
Mar 19 10:28:03 rame user.info RAME: Playing
Mar 19 10:28:06 rame user.info RAME: Player: sending play command, cursor 1458378423001114
Mar 19 10:28:06 rame user.info RAME: Stopped
Mar 19 10:28:06 rame user.info RAME: Playing file:////media/sdb1/musiikit/iasn_FI_009.mp3
Mar 19 10:28:08 rame user.info RAME: Stopped file:////media/sdb1/musiikit/iasn_FI_009.mp3
Mar 19 10:28:08 rame user.info RAME: Playing
Mar 19 10:28:11 rame user.info RAME: Player: sending play command, cursor 1458378423001116
Mar 19 10:28:11 rame user.info RAME: Stopped
Mar 19 10:28:11 rame user.info RAME: Playing file:////media/sdb1/musiikit/iasn_FI_011.mp3
Mar 19 10:29:13 rame user.info RAME: Stopped file:////media/sdb1/musiikit/iasn_FI_011.mp3
Mar 19 10:29:13 rame user.info RAME: Playing
Mar 19 10:29:23 rame user.info RAME: Player: sending play command, cursor 1458378423001122
Mar 19 10:29:23 rame user.info RAME: Stopped
Mar 19 10:29:23 rame user.info RAME: Playing file:////media/sdb1/musiikit/iasn_FI_016.mp3
Mar 19 10:29:23 rame kern.err kernel: [ 4955.404248] bcm2708-i2s 3f203000.i2s: I2S SYNC error!
Mar 19 10:29:25 rame user.info RAME: Stopped file:////media/sdb1/musiikit/iasn_FI_016.mp3
Mar 19 10:29:25 rame user.info RAME: Playing
Mar 19 10:30:23 rame user.info RAME: Player: sending play command, cursor 1458378423000032
Mar 19 10:30:23 rame user.info RAME: Stopped
Mar 19 10:30:23 rame user.info RAME: Playing file:////media/sda1/ivjtg_E_r720P.mp4
Mar 19 10:30:23 rame kern.err kernel: [ 5015.445849] bcm2708-i2s 3f203000.i2s: I2S SYNC error!

**Comment by viliman** [comment]
@jlauha any comments for this I2S Sync error

**Comment by jlauha** [comment]
As long as sound can be heard and there aren't audible problems, it should be harmless. It's seen very commonly seen in the rame log (and in other hardware used by the same audio card). Also earlier confirmed by tteras that it shouldn't matter. (based on info searched from the web...)

**Comment by fabled** [comment]
Yes, comments I've seen is that the I2S SYNC error is harmless and should be ignored. If it causes audible problems, we'll look at it. But I'll close this for now as "no fix is needed".
