### ISSUE TITLE
BUG: Backend: Uknown "ffprobe" error at startup 

### ISSUE THREAD

**Issue by HablasNapa** [rameplayerorg/rameplayer-defects#17]
Uknown error is generated at every start up called:
Mar 20 06:33:42 rame user.err RAME: /usr/share/rameplayer-backend/plugins/ffprobe.lua:23: attempt to index a nil value (global 'RAME')

Below is the entire log:
Mar 20 06:32:48 rame syslog.info syslogd started: BusyBox v1.24.1
Mar 20 06:32:49 rame daemon.info dhcpcd[1097]: dev: loaded udev
Mar 20 06:32:49 rame daemon.warn dhcpcd[1097]: all: IPv6 kernel autoconf disabled
Mar 20 06:32:49 rame daemon.info dhcpcd[1097]: forked to background, child pid 1101
Mar 20 06:32:49 rame kern.info kernel: [   14.947418] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:32:49 rame daemon.info dhcpcd[1101]: eth0: waiting for carrier
Mar 20 06:32:49 rame kern.info kernel: [   15.064274] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/mprisplayer.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/fw_upgrage.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/keyboard.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/logger.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/splash-screen.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/audio-control.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/rotary.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/restapi.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/file.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/auto-cfg-hw.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/fbcp-display.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/ffprobe.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/status-leds.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/automount.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/settings.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/version.lua: loaded
Mar 20 06:32:49 rame user.info RAME: Plugin /usr/share/rameplayer-backend/plugins/rameutil.lua: loaded
Mar 20 06:32:49 rame daemon.err kernel: [   15.477896] udevd[636]: specified group 'input' unknown
Mar 20 06:32:50 rame user.info RAME: No audio info stored - going with defaults
Mar 20 06:32:50 rame user.info RAME: firmware: 0.7.0
Mar 20 06:32:50 rame user.info RAME: backend: development
Mar 20 06:32:50 rame user.info RAME: hw_addon_info: RamePlayer (p.id:0x0001 v.:0x0002 uuid:dd9e43fe-52d2-4d69-8c74-f9e53a2a52d6)
Mar 20 06:32:50 rame user.info RAME: hw_base: Raspberry Pi 2 Model B Rev 1.1 (a01041) RamePlayer
Mar 20 06:32:50 rame user.info RAME: rame_cfg_info: id/cids=3C/3,4,5,6 id/eeprom_cids=3C/3,4,5,6 (RamePlayer chassis 1.0)
Mar 20 06:32:50 rame user.info RAME: ver_short: 0.7.0/3C:3C,a01041
Mar 20 06:32:50 rame user.info RAME: Playing
Mar 20 06:32:50 rame user.info ramefbcp[1237]: Primary display is 640 x 480
Mar 20 06:32:50 rame user.info ramefbcp[1237]: Second display is 160 x 128 16bpp
Mar 20 06:32:50 rame kern.warn kernel: [   15.580030] FAT-fs (sda1): utf8 is not a recommended IO charset for FAT filesystems, filesystem will be case sensitive!
Mar 20 06:32:50 rame kern.warn kernel: [   15.630970] FAT-fs (sdb1): utf8 is not a recommended IO charset for FAT filesystems, filesystem will be case sensitive!
Mar 20 06:32:51 rame daemon.info dhcpcd[1101]: eth0: carrier acquired
Mar 20 06:32:51 rame daemon.warn dhcpcd[1101]: all: IPv6 kernel autoconf disabled
Mar 20 06:32:51 rame daemon.info dhcpcd[1101]: eth0: adding address fe80::814c:5f1d:49ce:8803
Mar 20 06:32:51 rame daemon.err dhcpcd[1101]: if_addaddress6: Not supported
Mar 20 06:32:51 rame kern.info kernel: [   16.708118] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
Mar 20 06:32:51 rame daemon.info dhcpcd[1101]: DUID 00:01:00:01:1d:af:94:95:b8:27:eb:22:11:3f
Mar 20 06:32:51 rame daemon.info dhcpcd[1101]: eth0: IAID eb:30:f1:c6
Mar 20 06:32:51 rame daemon.info dhcpcd[1101]: eth0: soliciting a DHCP lease
Mar 20 06:32:51 rame daemon.info dhcpcd[1101]: eth0: offered 192.168.0.19 from 192.168.0.1
Mar 20 06:32:52 rame kern.info kernel: [   18.101824] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:32:52 rame daemon.info dhcpcd[1101]: eth0: probing address 192.168.0.19/24
Mar 20 06:32:54 rame daemon.err /etc/init.d/ntpd[1221]: start-stop-daemon: failed to start `/usr/sbin/ntpd'
Mar 20 06:32:54 rame daemon.err /etc/init.d/ntpd[1202]: ERROR: ntpd failed to start
Mar 20 06:32:55 rame kern.info kernel: [   20.626190] NET: Registered protocol family 10
Mar 20 06:32:55 rame auth.info sshd[1282]: Server listening on 0.0.0.0 port 22.
Mar 20 06:32:55 rame auth.info sshd[1282]: Server listening on :: port 22.
Mar 20 06:32:55 rame daemon.info init: starting pid 1286, tty '/dev/tty1': '/sbin/getty 38400 tty1'
Mar 20 06:32:55 rame daemon.info init: starting pid 1292, tty '/dev/ttyAMA0': '/sbin/getty  115200 ttyAMA0 '
Mar 20 06:32:55 rame daemon.info init: starting pid 1287, tty '/dev/tty2': '/sbin/getty 38400 tty2'
Mar 20 06:32:55 rame daemon.info init: starting pid 1289, tty '/dev/tty4': '/sbin/getty 38400 tty4'
Mar 20 06:32:55 rame daemon.info init: starting pid 1291, tty '/dev/tty6': '/sbin/getty 38400 tty6'
Mar 20 06:32:55 rame daemon.info init: starting pid 1290, tty '/dev/tty5': '/sbin/getty 38400 tty5'
Mar 20 06:32:55 rame daemon.info init: starting pid 1288, tty '/dev/tty3': '/sbin/getty 38400 tty3'
Mar 20 06:32:55 rame kern.info kernel: [   20.701931] uart-pl011 3f201000.uart: no DMA platform data
Mar 20 06:32:55 rame kern.info kernel: [   21.261840] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:32:57 rame daemon.info dhcpcd[1101]: eth0: leased 192.168.0.19 for 3600 seconds
Mar 20 06:32:57 rame daemon.info dhcpcd[1101]: eth0: adding route to 192.168.0.0/24
Mar 20 06:32:57 rame daemon.info dhcpcd[1101]: eth0: adding default route via 192.168.0.1
Mar 20 06:32:57 rame user.info RAME: IP 192.168.0.19
Mar 20 06:32:57 rame daemon.info dhcpcd[1101]: eth0: removing route to 192.168.0.0/24
Mar 20 06:32:58 rame kern.info kernel: [   24.421831] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:33:02 rame kern.info kernel: [   27.581825] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:33:05 rame kern.info kernel: [   30.741831] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:33:08 rame kern.info kernel: [   33.901829] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:33:11 rame kern.info kernel: [   37.061824] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:33:14 rame kern.info kernel: [   40.221828] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:33:17 rame kern.info kernel: [   43.381828] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:33:21 rame kern.info kernel: [   46.541834] cfg80211: Calling CRDA to update world regulatory domain
Mar 20 06:33:24 rame kern.info kernel: [   49.701829] cfg80211: Exceeded CRDA call max attempts. Not calling CRDA
**Mar 20 06:33:42 rame user.err RAME: /usr/share/rameplayer-backend/plugins/ffprobe.lua:23: attempt to index a nil value (global 'RAME')**
Mar 20 06:34:15 rame user.info RAME: Player: sending play command, cursor 1458455569000179
Mar 20 06:34:15 rame user.info RAME: Stopped
Mar 20 06:34:15 rame user.info RAME: Playing file:////media/sdb1/musiikit/iasn_FI_001.mp3
Mar 20 06:34:16 rame kern.err kernel: [  101.545229] bcm2708-i2s 3f203000.i2s: I2S SYNC error!
Mar 20 06:34:16 rame kern.err kernel: [  101.545601] arizona spi0.1: ASRC underclocked
Mar 20 06:34:23 rame user.info RAME: Stopped file:////media/sdb1/musiikit/iasn_FI_001.mp3
Mar 20 06:34:23 rame user.info RAME: Playing

**Comment by viliman** [comment]
@jlauha any comments?

**Comment by jlauha** [comment]
ffprobe.lua:23 is simply call to RAME.log. Should probably add simple validation (check for nil), assuming the issue is with "self.uri" ...

Not sure but I was under impression this is connected to #15.
