### ISSUE TITLE
BUG: Settings IP-address settings

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#18]
It's not possible to assign static ip-address to device.

![ip-address](https://cloud.githubusercontent.com/assets/17140545/13918645/5e149190-ef71-11e5-8ec3-ab0bf768a746.PNG)

Gui just says 'Saving admin settings failed', and nothing is written to <ip-address>:8000/log

**Comment by jlauha** [comment]
Does it work if alternative DNS is also set? (even if it is same with preferred DNS)

**Comment by HassuX** [comment]
Nope, did not found any working combination.

Tried with one, two or zero DNS-servers. With or without GW, tried different subnets etc.

**Comment by HassuX** [comment]
https://wiki.rameplayer.org/testreports:testreport_2016-03-21_13_52_settings_janne

**Comment by foilharp** [comment]
This error comes (or should come) if all the inserted values are valid, but something goes wrong in saving process otherwise. Is there any setting at all saved successfully on admin side? Will the device show "Restart pending" on LCD regardless?

**Comment by HassuX** [comment]
Device does not show restart pending after trying to save. NTP settings does not seem to save either, even though it does not give any error (there is a own ticket for that NTP settings).

Video output, audio output and device name (hostname) does save succesfully on admin page.

**Comment by foilharp** [comment]
Addressed in https://github.com/rameplayerorg/rameplayer-webui/commit/f41a12d2d5841eaebf1ff61144c0279b1dc70e71

**Comment by viliman** [comment]
@HassuX I think setting static IP works now and you have verified it? If so you can close the issue..

**Comment by HassuX** [comment]
Yes, static IP address works. @viliman
