### ISSUE TITLE
BUG: Settings: NTP-settings does not work

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#19]
Assigning NTP-server does not seem to do anything (it saves successfully, but loses entered value after browsing away from settings page.

Same thing with manual date field, it does not change anything. 

Manual time change = seems to go back in time for some minutes (I did not find any logic..), but does not change to desired time. And it allows impossible times to be entered, larges value that works is "29:99:99", so there are a bit too many hours, minutes and seconds of time at ramedev department...

Nothing is written to logs when saving.

**Comment by HassuX** [comment]
https://wiki.rameplayer.org/testreports:testreport_2016-03-21_13_52_settings_janne

**Comment by foilharp** [comment]
Addressed in https://github.com/rameplayerorg/rameplayer-webui/commit/8e90be72da6bde297c9716a950dcf098a1d209cf

**Comment by HassuX** [comment]
Manual settings work now, but ntp does not, setting hostname does nothing (afaik), and ntp service is not started.

**Comment by HassuX** [comment]
NTP works now.

But, if I set date & time manually & reboot device, it still has ntpd settings, ntpd starts, and it will change it's time from ntp server, so manual date & time does not stay, if there is ntp-server available and previously configured. You can, of course remove ntp server, then it words (ntpd tries to start, but crashes)

Don't know it this is intentionally like this or not?

Also (observations):
When using NTP, local web-ui-shows UTC(?) time, and local ui shows "UTC+0200" <time>, but actually it's +3 (OS shows EEST -> summertime)

And when using manual configuration, web-ui shows UTC time (and this is what you set to machine) but local-ui shows again "UTC+0200", and this time it actually is +2 to what you have set (OS shows EET).

**Comment by jlauha** [comment]
With recent fw (0.9.x), timezone of the device is now changed to be in Helsinki timezone, and local lcd screen should show time using the device time ("UTC+0300 hh:mm:ss" currently).

WebUI shows UTC time (intentionally, as no timezone selection is implemented). Although it should be stated in the UI that it's UTC time.

I'm unable to reproduce local screen showing "UTC+0200", any more details on how to get that to happen?

**Comment by HassuX** [comment]
Dummy me, you can reproduce it by giving date when normal time is used :)

So local ui actually shows it correctly, that part was bad testing..

**Comment by jlauha** [comment]
Thanks for checking.

That "configure time manually" setting is maybe a bit misleading if the ntp server address is left intact. But if player is not connected to internet, then the expected result is that ntp won't work (and shouldn't touch time), so the manual time setting should be a way to set device to correct time until it's connected to net.

**Comment by viliman** [comment]
Should this be dealed in webui show that if manual time is set no NTP information is send, because if NTP server is send the backend will take into use.

**Comment by foilharp** [comment]
Adderessed in https://github.com/rameplayerorg/rameplayer-webui/commit/af8771a0315b78283ff5b066dd9d5ae755e6e187

**Comment by HassuX** [comment]
WEB-ui now has comment that time is UTC, so for me, this can be closed. Misleading behavior about NTP settings might be discussed later if needed?
