### ISSUE TITLE
NEW FEATURE: Output always to headphones OR warning that it's disabled when only HDMI

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#20]
If audio port is selected to be 'HDMI', no sound is coming from headphones jack.

Either enable audio output to headphones jack or give some kind of warning when HDMI is selected to be only audio output device and:
- when adjusting headphones volume from web gui
- when using volume control in front panel of device

**Comment by viliman** [comment]
@fabled How feasible is the option of enabling audio output for the headphones? FYI @McLad76

**Comment by fabled** [comment]
We would need to add new audio clocking mode where HDMI is the master. I'd rather not try to implement at time being.

**Comment by viliman** [comment]
Would you @jlauha implement warning in the local UI. Can you make separate ticket for that in backend repo and refer it here?

**Comment by viliman** [comment]
@foilharp would you make same kind of ticket for the webui

**Comment by jlauha** [comment]
Local UI warning added in https://github.com/rameplayerorg/rameplayer-backend/commit/e8e41414c3a1f338184c91ba0a2fcc192de18bb0

**Comment by foilharp** [comment]
Addressed in https://github.com/rameplayerorg/rameplayer-webui/commit/f6e5788832f4bfda36a7ed156bae87a17d8b1b06

**Comment by HassuX** [comment]
Confirm with release 0.8.1
