### ISSUE TITLE
BUG: Warning that reboot is required is not shown in some cases

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#21]
Example:
- I change setting that requires reboot
- I get warning that it requires a reboot
- I reboot device
- I do not browse away and/or refresh settings page during reboot
- I change another setting that requires reboot 
- I do not get any warning on web-gui, LCD display on front panel does say 'restart pending'

**Comment by viliman** [comment]
fyi @foilharp

**Comment by foilharp** [comment]
Maybe because for some reason checkServerNotifications() in core/statusservice.js does not get fired. It maybe should do so explicitly always after $save gets through. </innerpondering>

**Comment by foilharp** [comment]
Addressed in https://github.com/rameplayerorg/rameplayer-webui/commit/616e95c1d3abaf7c5a77f206ccc82763a44eb147 
However, reboot of the web UI by navigating to http://device-ip/ is mandatory after rebooting the device itself. There-is-to-be a button in UI which does both reboots but thats another ticket :)

**Comment by viliman** [comment]
@HassuX is this now fixed (I know the whole chain should be more logical) but at least the bug that you described. If ok you could close by saying "fix verified in v.0.7.4"

**Comment by HassuX** [comment]
Fix verified in v0.7.4 @viliman
