### ISSUE TITLE
Feature request: Reboot button on settings page

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#22]
Some setting changes require device to be rebooted before settings are applied (ex. video output resolution).

It would be nice to have a reboot button (with confirmation ;)) to restart device, without needing to poweroff -> poweron physically.

**Comment by viliman** [comment]
Comments? Automatic Reboot with Dialog? Or/And Reboot button? I would prefer automatic reboot with dialog confirmation.. @McLad76 @mkheikkinen @fabled @jlauha @iqqmuT @foilharp

**Comment by jlauha** [comment]
Reboot button (one can change multiple things before rebooting)
=> confirmation dialog in webui: "Are you sure? Reboot/Cancel"
=> wait screen: "Please wait ... rebooting (60 seconds)"
=> automatic refresh/reload in browser to root page (assuming same IP address!)

About that last step: might want to add warning about need to manually check for ip if it changes after boot (in case of DHCP). If using static ip and it has been changed, the autorefresh could directly reload the webui from the new IP...

**Comment by HassuX** [comment]
Tested with version 0.9.0, works.
