### ISSUE TITLE
BUG: DHCP-server does not work

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#25]
Multiple issues with this one.
1. udhcpd service is always in 'crashed' state after reboot, does not matter if DHCP-server is enabled or not in admin-page. It works if you go to OS and restart service.
2. There are some pre-defined settings in /etc/udhcpd.conf, at least following should be removed:
   opt     wins    192.168.10.10
   option  dns     129.219.13.81   # appended to above DNS servers for a total of 3

My opinion is that:
- if dhcp-server is disabled in admin page = udhcpd service is stopped
- if dhcp-client is enabled in admin page = udhcpd service is stopped
  So udhcpd service is started, when it is enabled in admin page

Tested on version 0.7.3 (milestone missing..)

**Comment by HassuX** [comment]
Still the same with 0.8.1

And actually noticed following:
If you only have one DNS-server in static IP-settings, you cannot enable DHCP on web-ui. Gives error 'Type error: Cannot read property 'error' of null'. Don't remember if this was on earlier versions.

**Comment by HassuX** [comment]
Yet again UI has a bit changed on version 0.8.2:

Still getting error on saving settings if DHCP-server is enabled and secondary DNS-server in static IP-settings is empty.

Also, now after reboot all DHCP-server settings are cleared (in a way, better behavior since DHCP-server still does not work...)

**Comment by jlauha** [comment]
Might want to add file /etc/conf.d/udhcpd containing: UDHCPD_OPTS="-S" (udhcpd log to syslog)

**Comment by jlauha** [comment]
The udhcpd seems to work when introducing a long enough delay ("sleep 5" or so) in /etc/init.d/udhcpd ... This is a hack - after this even service status query will sleep for a while first. [Edited]

It seems despite that udhcpd config has "need net" (provided by dhcpcd), udhcpd gets chance to start itself before eth0 is up.

Relevant log rows:
May 23 13:42:01 rame daemon.info dhcpcd[1121]: eth0: probing address 10.0.0.16/24
...
May 23 13:42:05 rame daemon.info udhcpd[1328]: udhcpd (v1.24.2) started
May 23 13:42:05 rame daemon.err udhcpd[1328]: max_leases=235 is too big, setting to 2
May 23 13:42:05 rame daemon.err udhcpd[1328]: can't open '/var/lib/udhcpd/udhcpd.leases': No such file or directory
May 23 13:42:05 rame daemon.err udhcpd[1328]: is interface eth0 up and configured?: Address not available
...
May 23 13:42:06 rame daemon.info dhcpcd[1121]: eth0: using static address 10.0.0.16/24
May 23 13:42:06 rame daemon.info dhcpcd[1121]: eth0: adding route to 10.0.0.0/24
May 23 13:42:06 rame daemon.info dhcpcd[1121]: eth0: adding default route via 10.0.0.4
May 23 13:42:06 rame user.info RAME: IP 10.0.0.16

Note the order.

**Comment by jlauha** [comment]
This should be mostly fixed now with this commit in addition to the previous ones: https://github.com/rameplayerorg/rameplayer-alpine/commit/1547c326c58ee9494a811bc0e5bfc840e6e93f3d

There's still one remaining bug:
If dynamic IP was being used, and switching to static IP and dhcp server mode (at the same time), then  backend doesn't save the static ip settings.
Workaround: Change to static ip & fill in settings & save. After that, enable dhcp server and enter range, then save again.
