### ISSUE TITLE
BUG: Audio output is not in sync when 'Both' is selected

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#26]
When both (hdmi & analog) audio ouput is selected, HDMI-audio is not in sync.

This is a known issue in platform (raspberry)

**Comment by viliman** [comment]
Warning of that should be good to add though.
Created a issue for that:
https://github.com/rameplayerorg/rameplayer-webui/issues/28

**Comment by foilharp** [comment]
Adressed in https://github.com/rameplayerorg/rameplayer-webui/commit/9b26cc9d1cb2b716a47c1393cffbfc9ad71604e6
