### ISSUE TITLE
BUG: When setting Static IP that is already in use the webui will report the wrong IP

### ISSUE THREAD

**Issue by viliman** [rameplayerorg/rameplayer-defects#27]
Steps to reproduce:
1. Have another computer in LAN with address A
2. Set the RAME to static IP with address A (same as the other computer)

Outcome:
Local UI will show the correct IP but the webui shows the one is set.
![img_2237](https://cloud.githubusercontent.com/assets/13642417/14706249/3beca888-07c6-11e6-851b-1a9e0414fb05.JPG)
![bug_ip_exists_in_lan](https://cloud.githubusercontent.com/assets/13642417/14706262/4f5b771e-07c6-11e6-9721-234c2461f076.png)

@HassuX Please can you make a new test case for this

**Comment by HassuX** [comment]
Couple of comments.

I tested this, and I'm able to reproduce.

So, originally my rame was using DHCP, and received address 192.168.1.198 from DHCP server (WLAN router).

I assigned IP-address 192.168.1.50 to my laptop.

I assigned IP-address 192.168.1.50 to rame

When rebooting device, this is what log says:
Apr 25 10:12:14 JanneRame2 daemon.info dhcpcd[1113]: eth0: carrier acquired
Apr 25 10:12:14 JanneRame2 daemon.warn dhcpcd[1113]: all: IPv6 kernel autoconf disabled
Apr 25 10:12:14 JanneRame2 daemon.info dhcpcd[1113]: eth0: adding address fe80::c347:2d23:eb72:c3f0
Apr 25 10:12:14 JanneRame2 daemon.err dhcpcd[1113]: if_addaddress6: Not supported
Apr 25 10:12:14 JanneRame2 kern.info kernel: [   17.399494] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xC5E1
Apr 25 10:12:14 JanneRame2 daemon.info dhcpcd[1113]: DUID 00:01:00:01:1d:af:94:95:b8:27:eb:22:11:3f
Apr 25 10:12:14 JanneRame2 daemon.info dhcpcd[1113]: eth0: IAID eb:12:11:2f
Apr 25 10:12:14 JanneRame2 daemon.info dhcpcd[1113]: eth0: probing address 192.168.1.50/24
Apr 25 10:12:14 JanneRame2 daemon.err dhcpcd[1113]: eth0: hardware address e8:b1:fc:83:64:9a claims 192.168.1.50
Apr 25 10:12:15 JanneRame2 daemon.info dhcpcd[1113]: eth0: soliciting a DHCP lease
Apr 25 10:12:15 JanneRame2 daemon.info dhcpcd[1113]: eth0: offered 192.168.1.198 from 192.168.1.1
Apr 25 10:12:15 JanneRame2 daemon.info dhcpcd[1113]: eth0: probing address 192.168.1.198/24
Apr 25 10:12:18 JanneRame2 kern.info kernel: [   21.494350] NET: Registered protocol family 10
Apr 25 10:12:20 JanneRame2 daemon.info dhcpcd[1113]: eth0: using static address 192.168.1.198/24
Apr 25 10:12:20 JanneRame2 daemon.info dhcpcd[1113]: eth0: adding route to 192.168.1.0/24
Apr 25 10:12:20 JanneRame2 daemon.info dhcpcd[1113]: eth0: adding default route via 192.168.1.1
Apr 25 10:12:20 JanneRame2 user.info RAME: IP 192.168.1.198
Apr 25 10:12:20 JanneRame2 daemon.info dhcpcd[1113]: eth0: removing route to 192.168.1.0/24

So it detects colliding IP-address, and failbacks to DHCP (at least what I understand...)

So, bug in here is in web-ui, that sould show real ip-address?

Maybe also warning about colliding IP-address and that failback to dhcp has been done?

@viliman

**Comment by viliman** [comment]
Thanks for debugging this! I think the RAME is here doing exactly as we would want it to be doing but we need to provide better feedback for the user in the webui if possible. We toss the ball to @foilharp to be implemented

**Comment by foilharp** [comment]
Addressed in https://github.com/rameplayerorg/rameplayer-webui/commit/39fe18e88003c69aed92d64a44edeb7a3c759127

**Comment by HassuX** [comment]
UI comment works in 0.8.1
