### ISSUE TITLE
Feature request: Cluster: Export/import all settings made in GUI

### ISSUE THREAD

**Issue by HablasNapa** [rameplayerorg/rameplayer-defects#28]
This came up in the cluster testing and would also be good to have in rameplayer overall.

The export/import should include:
- Devices in the cluster
- Playlists in the cluster

Presently these have to be entered manually each time even when there is no change in the cluster setup.

**Comment by viliman** [comment]
https://github.com/rameplayerorg/rameplayer-webui/issues/17

this should be implemented and there is ticket for 
https://github.com/rameplayerorg/rameplayer-webui/issues/18

@iqqmuT can comment what is the status

**Comment by iqqmuT** [comment]
@HablasNapa what did you mean by "have to be entered manually each time"? Like after closing the browser or rebooting the device?

We should get permanent playlists in somewhere near future, does that affect this feature request?

**Comment by viliman** [comment]
What is the status at the moment?

**Comment by iqqmuT** [comment]
Currently when exporting/importing cluster configuration from WebUI it includes devices and playlist synchronization data (only references, not actual playlists). Playlists are now persisted in backend so is there something more to be done?

**Comment by viliman** [comment]
Don't know would be the honest answer :) Let's go with this version and verification team can make complain with a bug issue if thinks don't work as expected.
