### ISSUE TITLE
Settings: Admin settings: No navigation buttons to get back to User settings / Playlists

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#3]
When you are in Admin settings page, there are no navigation buttons that would get you back to USB / Playlists / User settings page (buttons in picture, they are shown on all other pages):

![image](https://cloud.githubusercontent.com/assets/17140545/13079661/0d5db1c2-d4ce-11e5-9294-79e46c7d4304.png)

**Comment by viliman** [comment]
@McLad76 and @iqqmuT thumbs up or down

**Comment by foilharp** [comment]
Just dimes... In end use, there is meant to be username/password check (possibly by HTTP server) before loading admin settings making it harder to arbitrary user accidentally wander there at all. Also changes made to admin settings often need reboot of device using physical button in box, which naturally would/should reboot WUI. If after settings changing reboot should show admin settings page, that is another question.

**Comment by McLad76** [comment]
It would be nice to have navigation button anyway, because sometimes you just want to check if configuration is Ok.

**Comment by viliman** [comment]
Assigning this for @foilharp todo

**Comment by foilharp** [comment]
Bug addressed in https://github.com/rameplayerorg/rameplayer-webui/commit/d20baf94a7243474a74c3ef24def3548d56562b6
