### ISSUE TITLE
BUG: Cluster: Playlists are lost if a device in cluster reboots

### ISSUE THREAD

**Issue by HablasNapa** [rameplayerorg/rameplayer-defects#30]
During testing one of the devices in cluster was restarted to see what would happen when power and network was restored.

The device automatically returns to the cluster but without the playlist that was set for it pre-boot.

The result was that the first item in the directory was played when a command of "**play**" was given from the GUI to the cluster with the delay set for that device.

**Comment by HablasNapa** [comment]
Duplicate case.

Going to sleep...

**Comment by viliman** [comment]
https://github.com/rameplayerorg/rameplayer-defects/issues/32
