### ISSUE TITLE
USB don't let me select root folder anymore

### ISSUE THREAD

**Issue by TaruVare** [rameplayerorg/rameplayer-defects#34]
Issue is not related to any of my test cases, but I noticed that now in any browser I cannot get back to the USB root folder.

Steps to reproduce:
1. Select USB (FRIDAY in UI now)
2. Open any subfolder, e.g. Finnish
Results: there is no root folder visible, to get back (see picture)

![testing_080516_dont let back to usb root](https://cloud.githubusercontent.com/assets/17190958/15098844/51d3b790-154f-11e6-9733-ad151c0fd603.PNG)

**Comment by jlauha** [comment]
Also noted here: https://github.com/rameplayerorg/rameplayer-webui/issues/32

**Comment by fabled** [comment]
fixed 0.8.1, please verify

**Comment by McLad76** [comment]
Works in 0.8.3

**Comment by TaruVare** [comment]
Agree, this works now.
