### ISSUE TITLE
BUG: Edited playlist name is changed back to the old name after reboot

### ISSUE THREAD

**Issue by TaruVare** [rameplayerorg/rameplayer-defects#35]
Test case: Rename saved playlist

Steps to reproduce:
1. Create a saved playlist

![080516_saved playlist](https://cloud.githubusercontent.com/assets/17190958/15099094/3ccd17b4-1555-11e6-8432-b196f6a2fef6.PNG)
1. Rename playlist

![080516_renamed playlist](https://cloud.githubusercontent.com/assets/17190958/15099095/422e8404-1555-11e6-98d2-04a7ae918343.PNG)
1. Reboot RaMe player
2. Changed playlist name is again the old one

![080516_saved playlist after reboot](https://cloud.githubusercontent.com/assets/17190958/15099097/51010ad8-1555-11e6-89b5-124c9d2611dd.PNG)

**Comment by iqqmuT** [comment]
Backend returns error 404 when editing playlist properties. Apparently this function is missing from backend?

**Comment by TaruVare** [comment]
This issue still exists in 0.8.3. Issue is the same with any playlist editing, name and storage changed, or changing list as autoplay.

**Comment by TaruVare** [comment]
This issue is fixed in 0.91
