### ISSUE TITLE
BUG: rame 'freaks out' if you insert 'empty' USB-disk

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#36]
Conditions:
- USB-autoplay is on
- There is only 'System Volume Information' (and .rameplaylists.json) on USB-disk
- You reboot rame with usb-connected or insert usb

Symptoms: 
- green and yellow LED are on in local-ui
- if USB-disk was inserted when rame was already on, on-screen display shows 'stopped box' in down left corner
- is USB disk is inserted while rame boots-up, there reads 'System volume information' as a filename on on-screen display.
- <rameip>:8000/log goes unresponsible

Only way to recover is reboot.

Side-note, 'System volume information' folder is always created when you insert USB-disk to Windows machine, and it's a bit tricky to remove that in Windows.

**Comment by jlauha** [comment]
I'm able to reproduce this - backend process indeed becomes totally unresponsive in that case. Will try to investigate further...

**Comment by fabled** [comment]
Probably gets stuck in the autoplay loop. Should add a failsafe mechanism that if RAME.main loop tries to play same item again during one cycle it stops autoplay mode.

**Comment by jlauha** [comment]
Should be fixed in next build (backend issue: https://github.com/rameplayerorg/rameplayer-backend/issues/45)

**Comment by viliman** [comment]
Thanks @jlauha  we are really agile here tonight. Assigning this back to verification can be closed when fix verified

**Comment by HassuX** [comment]
Confirm that this is fixed in version 0.8.1
