### ISSUE TITLE
Settings: Admin settings: NTP Server hostname allows special characters

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#4]
Hostname field on NTP server settings allows use of 'illegal' characters, like ääkköset.

![image](https://cloud.githubusercontent.com/assets/17140545/13080463/62cba922-d4d1-11e5-9d95-613e6aabd6f5.png)

**Comment by foilharp** [comment]
Bug addressed in https://github.com/rameplayerorg/rameplayer-webui/commit/44c5b27a688f06af7fed5589f2e7ce2c62e6334c

**Comment by viliman** [comment]
@HassuX is this fix now verified?

**Comment by HassuX** [comment]
Yes, this is fixed (tested on v.0.7.4)
