### ISSUE TITLE
BUG: Playlists: Removing lowest playlist removes the upper one also

### ISSUE THREAD

**Issue by HablasNapa** [rameplayerorg/rameplayer-defects#43]
Removing the lowest playlist when 2 or more playlist are available also removes the upper one.

![step1](https://cloud.githubusercontent.com/assets/17044875/15360708/53e68e7a-1d17-11e6-8b4e-c94700800202.PNG)
![step2](https://cloud.githubusercontent.com/assets/17044875/15360707/53e382f2-1d17-11e6-9799-8675e01ac977.PNG)
![step3](https://cloud.githubusercontent.com/assets/17044875/15360709/53e83e78-1d17-11e6-90ff-4a3ce0421946.PNG)

If the device is rebooted, the "upper" playlist reappears after reboot back to playlists.

![step4](https://cloud.githubusercontent.com/assets/17044875/15360816/d7863b90-1d17-11e6-8707-09f4938f551e.PNG)

**Comment by viliman** [comment]
I assume that this is backend bug but please correct me if I'm wrong.. 

cc @iqqmuT

**Comment by fabled** [comment]
Btw. this is likely same bug as #12. Both issues should be fixed in the 0.8.2 firmware to come soon.

**Comment by viliman** [comment]
please verify

**Comment by McLad76** [comment]
Works in 0.8.3

**Comment by TaruVare** [comment]
This is the same bug as in issue #12 
Issue is verified to be fixed in IE 11, Chrome and Firefox. This can be closed.
