### ISSUE TITLE
BUG: Playlist storage shows always 'RAME'

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#45]
1. Create playlist -> save to USB disk
2. Edit saved playlist -> Storage shows 'RAME'

**Comment by viliman** [comment]
cc @iqqmuT @TaruVare

**Comment by fabled** [comment]
assigning for @iqqmuT for fixing webui

**Comment by fabled** [comment]
webui should fixed now too, should be fixed in upcoming 0.8.2 image

**Comment by viliman** [comment]
Please verify

**Comment by McLad76** [comment]
Works in 0.8.3
