### ISSUE TITLE
BUG: USB-disks don't work

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#46]
USB-disk is not correctly recognized in in rame Web-UI.

When you insert USB-disk, behavior on UI is this:
![image](https://cloud.githubusercontent.com/assets/17140545/15453224/6fcfac82-2016-11e6-9206-4fee69e5bc88.png)

But, if you wait for some time (in this log case, about two minutes) it shows it correctly. Once it took about 10 minutes.

Log file is attached:
[rame_usb_log.txt](https://github.com/rameplayerorg/rameplayer-defects/files/276239/rame_usb_log.txt)

In logfile, USB disk is attached on timestamp: "17:34:05"
It starts to work on UI on timestamp "17:36:22"

Behavior is about the same, whether you insert disk after rame is up, or if you reboot rame with USB-disk inserted.

And at least once, after USB disk was initialized correctly on web-UI, I rebooted, and everything worked immediately (video autoplayded etc). But after removing USB and re-inserting it, it tooked again minutes before it was recognized in UI. Also video does not autoplay if USB is not recognized immediately. But I was not able to reproduce this behavior. 

When looking in shell, everything is ok, so USB-disk is mounted as it should immediately after inserting.

**Comment by viliman** [comment]
Blocker must be fixed and verified next week!

cc @iqqmuT @McLad76 @TaruVare

**Comment by HassuX** [comment]
Tested in 0.9.0, works.
