### ISSUE TITLE
BUG: Playback continues after EOF (in rare cases?)

### ISSUE THREAD

**Issue by viliman** [rameplayerorg/rameplayer-defects#5]
In local LCD the screen is black and time is running both in local UI and Web UI
![421232455_5903711901006784348](https://cloud.githubusercontent.com/assets/13642417/13664584/d4c99df4-e6b0-11e5-9b02-c277674b5a14.jpg)

**Comment by fabled** [comment]
I have not been able to reproduce this. This was a known issue on earlier versions. Please comment if this has been reproduced with >0.7.0 or newer firmware.

**Comment by fabled** [comment]
We have not been able to reproduce this. Please re-open if someone can reproduce with recent firmware version.
