### ISSUE TITLE
BUG: Unable to set continuous play when saving a playlist

### ISSUE THREAD

**Issue by eharkovs** [rameplayerorg/rameplayer-defects#52]
When a new playlist is saved with continuous play enabled, either to the device or to USB drive, the setting is not persisted - in the properties edit pop-up it is unchecked.

**Comment by HassuX** [comment]
I can confirm this.

Create a playlist
Select "Continuous play, repeating all" (or "Play this when device starts" which will automatically select Coninuous play..)
Save playlist
Reboot device

After reboot, "Continuous play, repeating all" is no longer selected.

**Comment by fabled** [comment]
Backend does not yet support this feature. Planned for this week.

**Comment by HassuX** [comment]
Works now with v0.9.1.

Did not seem to work with 'old' playlist, but when creating new playlist, it worked as it should.
