### ISSUE TITLE
BUG: secondary DNS setting is does not show in web-ui after reboot

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#55]
If setting two DNS-servers, secondary is lost after reboot in web-ui.

So:
- You set secondary DNS-address and reboot
- After reboot, secondary DNS-address is in place at OS-level, but it does not show on web-ui
- If you now save settings again, without giving ip-address of secondary DNS again, you will only have one DNS-server in resolv.conf

It seems that web-ui does not read secondary dns server from some settings file?

**Comment by jlauha** [comment]
Fixed in https://github.com/rameplayerorg/rameplayer-backend/commit/9220e12ca441a09d85b05f119acace5467cee2e1

**Comment by HassuX** [comment]
Fixed (v.1.0.4)
