### ISSUE TITLE
BUG: admin settings shows "Could not load list of firmwares available for upgrade."

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#56]
Even though I'm able to see list of firmwares and upgrade, admin settings page shows
'Could not load list of firmwares available for upgrade.'

![image](https://cloud.githubusercontent.com/assets/17140545/15800891/8075a672-2a8e-11e6-8556-943ff6947a02.png)

**Comment by foilharp** [comment]
Addressed in https://github.com/rameplayerorg/rameplayer-webui/commit/a96391a16245166e602964b416e12adb2659e4e5

**Comment by HassuX** [comment]
fixed on 1.0.3
