### ISSUE TITLE
BUG: settings, "Automatically play files from USB" checkbox misbehavior

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#59]
Select box does not behave correctly.

If this setting is not selected, and you try to select it, box is not filled with 'check' mark. It does change setting and saves it, but ui does not show it (also it does not show 'option saved' message).

When you reboot device, or refresh page, it shows setting correctly. 

Deselecting checkbox works correctly.

Tested with multiple browsers (chrome, firefox, edge).

**Comment by foilharp** [comment]
Addressed in https://github.com/rameplayerorg/rameplayer-webui/commit/c2d476225f259d517b77bc4435201bf97dd221bd

**Comment by HassuX** [comment]
Fixed on 1.0.3
