### ISSUE TITLE
BUG: Check item name in a playlist

### ISSUE THREAD

**Issue by TaruVare** [rameplayerorg/rameplayer-defects#6]
Test case ID: PL_MUST_3
Browser: Chrome, version 49.0.2623.87 m, Mozilla Firefox 35.0.1 and IE 11

Item title doesn't show in playlist for item that does have name: screen shot Check item name shows the title that has name, but Check item and name and length test case fails - screen shot shows that name don't appear in the list.

![check item name 160316](https://cloud.githubusercontent.com/assets/17190958/13815394/0d1688d4-eb93-11e5-81c6-afc13fb20526.PNG)

[Check item name and length test case fails 160316.txt](https://github.com/rameplayerorg/rameplayer-defects/files/176120/Check.item.name.and.length.test.case.fails.160316.txt)

![check item name and check item length in a playlist_failed_160316](https://cloud.githubusercontent.com/assets/17190958/13815185/3dd09ca4-eb92-11e5-8b9f-2c3b0ea5fedc.PNG)

**Comment by fabled** [comment]
https://github.com/rameplayerorg/rameplayer-backend/commit/2caa23d8cf85404637e9be66cb899b4d4613a925 probably fixes this too.

**Comment by fabled** [comment]
Fix verified.
