### ISSUE TITLE
BUG: Playlist: Remove item from worklist

### ISSUE THREAD

**Issue by TaruVare** [rameplayerorg/rameplayer-defects#61]
PL_MUST_5 Remove item from worklist

If any item is rearranged before another item is removed from the worklist, the rearranged item returns back to its original position in worklist.

Issue appears in all browsers.

Steps to reproduce:
1. Add several items to the worklist
2. Rearrange one item, e.g. last to first
3. Remove any another item
4. Rearranged item is returned back to original position - e.g. to last

Issue is not high importance, as worklist is not necessarily required to use this way. Rearranging items works in saved playlists, and those should be rather used when playlists are created.

**Comment by viliman** [comment]
cc @fabled

**Comment by iqqmuT** [comment]
Moving items inside work list is broken, you can try also:
1. Add several items to the worklist
2. Rearrange one item
3. Reload the page
4. Items are back in original order.

Backend returns HTTP status code `405 Method Not Allowed` when WebUI sends
`PUT http://backend/lists/default/items/itemid` with payload `{ afterId: null }`

**Comment by TaruVare** [comment]
Fixed in 1.0.3
