### ISSUE TITLE
Issue: autoplay list starts playing before "waiting for device to restart" dialog is closed

### ISSUE THREAD

**Issue by TaruVare** [rameplayerorg/rameplayer-defects#62]
Autoplay playlists begin playing before device is fully restarted and webui is back to responsive state

**Comment by iqqmuT** [comment]
WebUI reconnects to the backend as fast as it can, so only solution here is to do something in backend:
- delay before autoplay starts
- get network connection up faster

**Comment by fabled** [comment]
It is working as designed. The webui can be closed after reboot request (or network cable can be disconnected after config is done), and the device is expected to start autoplaying. There's no point to wait for webui during startup.
