### ISSUE TITLE
BUG: saving admin settings does not require reboot when changing dhcp-server settings

### ISSUE THREAD

**Issue by HassuX** [rameplayerorg/rameplayer-defects#66]
When you change dhcp-server settings and save them, rame does not ask you to reboot device, even though it is required before settings are applied (read: before dhcp-server is starter or stopped)

**Comment by jlauha** [comment]
oops, accidentally auto-closed the issue; reopening to left open until validated with a new FW version...

**Comment by HassuX** [comment]
Fixed in release 1.0.4 (does not require autoboot, saving change service status)
