### ISSUE TITLE
BUG: Check item length in a playlist

### ISSUE THREAD

**Issue by TaruVare** [rameplayerorg/rameplayer-defects#7]
Test case ID: PL_MUST_4
Browser: Chrome, version 49.0.2623.87 m, Mozilla Firefox 35.0.1 and IE 11

Item lengths are missing from all items.

[Check item name and length test case fails 160316.txt](https://github.com/rameplayerorg/rameplayer-defects/files/176131/Check.item.name.and.length.test.case.fails.160316.txt)

![check item name and check item length in a playlist_failed_160316](https://cloud.githubusercontent.com/assets/17190958/13815510/8b244a04-eb93-11e5-8aaf-dbdc3011f5a1.PNG)

**Comment by fabled** [comment]
https://github.com/rameplayerorg/rameplayer-backend/commit/2caa23d8cf85404637e9be66cb899b4d4613a925 probably fixes this too.

**Comment by fabled** [comment]
Fix verified.
