### ISSUE TITLE
BUG: Rearrange items in a playlist

### ISSUE THREAD

**Issue by TaruVare** [rameplayerorg/rameplayer-defects#8]
Test case ID: PL_MUST_6
Browser: Chrome, version 49.0.2623.87 m
-> works in Mozilla

Items cannot be rearranged in a playlist. Cursor changes as a grabbing tool when moved above list icon on the right side of playlist item, but items don't move.

![rearrange items in a playlist fails 160316](https://cloud.githubusercontent.com/assets/17190958/13815843/d9235550-eb94-11e5-9448-51c24e672dc1.PNG)
[Rearrange items in a playlist fails 160316.txt](https://github.com/rameplayerorg/rameplayer-defects/files/176156/Rearrange.items.in.a.playlist.fails.160316.txt)

**Comment by viliman** [comment]
Works in IE11

**Comment by TaruVare** [comment]
Rearraging playlist items works now in Chrome browser as in IE11 and Mozilla Firefox.
